FROM golang:1.19.3 as download

WORKDIR /go/src/socheap

COPY go.mod .
COPY go.sum .

RUN go mod download

FROM golang:alpine as build

RUN apk --no-cache add tzdata

WORKDIR /go/src/socheap

COPY . .

COPY --from=download /go/pkg/mod/ /go/pkg/mod/

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o socheap cmd/socheap/main.go

FROM scratch as image

COPY --from=build /go/src/socheap/socheap .
COPY --from=build /go/src/socheap/.env .
COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=America/Sao_Paulo

EXPOSE 8080

CMD ["/socheap"]