version: "3.9"

services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /Users/marcon/desenvolvimento/go/messages/amqp/dev-rabbitmq/data/:/var/lib/rabbitmq
      - /Users/marcon/desenvolvimento/go/messages/amqp/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - dev-network

  sender:
    container_name: sender
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile-sender
    restart: always
    networks:
      - dev-network
    depends_on:
      - message-broker

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile-consumer
    restart: always
    networks:
      - dev-network
    depends_on:
      - sender
      - message-broker

networks:
  dev-network:
    name: dev-network
    driver: bridge
    external: true