FROM golang:1.19.3 as download

WORKDIR /go/src/consumer

COPY go.mod .
COPY go.sum .

RUN go mod download

FROM golang:1.19.3 as build

WORKDIR /go/src/consumer

COPY . .

COPY --from=download /go/pkg/mod/ /go/pkg/mod/

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o consumer cmd/consumer/main.go

FROM scratch as image

COPY --from=build /go/src/consumer/consumer .

CMD ["/consumer"]